<?php
/**
 * @var $this Tool\View
 */
?>
<?php echo $this->renderView('partials/editor') ?>
<div class="screen output" id="result">
    <?php
    /**
     * @var $this Tool\View
     */
    echo $this->output;
    ?>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $('#result').data('success', function(response){
            if(response.output){
                $('#result').html(response.output);
            }
        });

    });
</script>