<?php
/**
 * @var $this Tool\View
 */
?>
<div class="span5">
    <?php echo $this->renderView('form') ?>
</div>
<div class="span5 screen output" id="result">
    <?php
    /**
     * @var $this Tool\View
     */
    echo $this->output;
    ?>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $('#eval-btn').on('click', function(){
            var result = $('#result');
            try {
                result.html(eval($('#code').val()) || '');
            }catch (e) {
                result.html(e.message);
            }finally {
                //$('#result').html(result);
            }
            return false;
        });
    });
</script>