<div class="row">
    <div id="editor" class="output span6"><?php echo htmlentities($this->code) ?></div>
    <div id="result" class="output span5"><?php echo $this->output ?></div>
</div>
<div class="row">
    <div class="span6">
        <a href="#" class="btn btn-danger" id="reset-btn">reset</a>
        <a href="#" class="btn btn-large btn-success pull-right" id="eval-btn">EVAL</a>
    </div>
</div>
<script type="text/javascript" src="/js/code.js"></script>