<?php
/**
 * @var $this Tool\View
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Developer Tools</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="3axap4eHko">

    <!-- Le styles -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="/css/main.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="/js/html5shiv.js"></script>
    <![endif]-->

    <!--
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="../assets/ico/favicon.png">
    -->
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="/ace/ace.js" charset="utf-8"></script>
</head>

<body>

<div class="container">
        <div class="navbar navbar-inverse">
            <div class="navbar-inner">
                <div class="container">
                    <a href="//tools" class="brand">Developer Tools</a>
                    <ul class="nav">
                        <li><a href="#javascript">JS</a></li>
                        <li><a href="#php">PHP</a></li>
                        <li><a href="#mysql">MYSQL</a></li>
                        <li><a href="#about">ABOUT</a></li>
                    </ul>
                </div>
            </div>
        </div><!-- /.navbar -->
    <div id="content">

    </div>
</div> <!-- /container -->
<hr>
<div class="container">
    <div class="footer">
        <p>&copy; Company 2013</p>
    </div>
</div>

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script type="text/javascript" src="/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/js/main.js"></script>
</body>
</html>
