<?php
/**
 * @var $this Tool\View
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Developer Tools</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="3axap4eHko">

    <!-- Le styles -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="/css/main.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="/js/html5shiv.js"></script>
    <![endif]-->

    <!--
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="../assets/ico/favicon.png">
    -->
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="/ace/ace.js" charset="utf-8"></script>
</head>

<body>
<div id="wrap">
    <div class="container">
        <div class="navbar navbar-inverse">
            <div class="navbar-inner">
                <div class="container">
                    <a href="//tools" class="brand">Developer Tools</a>
                    <ul class="nav">
                        <li><a href="/#javascript" class="navigation">JS</a></li>
                        <li><a href="/#php" class="navigation">PHP</a></li>
                        <li><a href="/#sql" class="navigation">SQL</a></li>
                        <li><a href="/#about" class="navigation">ABOUT</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b class="caret"></b> CONFIG </a>
                            <ul class="dropdown-menu config config-dropdown">
                                <li class="nav-header">Database</li>
                                <li>
                                    <input type="text" id="dbName" placeholder="DB Name">
                                </li>
                                <li>
                                    <input type="text" id="dbHost" placeholder="DB Host">
                                </li>
                                <li>
                                    <input type="text" id="dbUsername" placeholder="DB Username">
                                </li>
                                <li>
                                    <input type="text" id="dbPassword" placeholder="DB Password">
                                </li>
                                <li class="divider"></li>
                                <li>
                                    <div>
                                        <a class="btn btn-success pull-right config-save">OK</a>
                                        <a class="btn btn-danger">Cancel</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div><!-- /.navbar -->
        <div class="span12">
            <div class="row" id="messages"></div>
            <div id="content"></div>
        </div>
    </div> <!-- /container -->
</div>
<hr/>
<div class="container">
    <div class="footer">
        <p>&copy; Company 2013</p>
    </div>
</div>

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script type="text/javascript" src="/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/js/layout.js"></script>

</body>
</html>
